#404_Martijn > Display screen when user has been caught
imfi-jz/SOPROJ11Q-Mobile pull request #101
Opened 2021-06-14 16:48 UTC by Ghoster524

2021-06-14 16:49 UTC, Ghoster524 commented
Met dit PR zou het moeten zijn gefixt wanneer een dief is opgepakt. Wat er mis ging, wat niet te merken is op een emulator, is dat een dief wordt opgepakt op basis van de locatie. Waarschijnlijk versprong een dief telkens op de kaart, dus nu zet ik de `userId` in de tag van een dief en als die is opgepakt, dan wordt het id eruit gehaald.

2021-06-15 14:04 UTC, imfi-jz requested changes
Ik testte als agent in mijn emulator en boef op mijn telefoon:

Als boef kreeg ik een error in de thief caught event :/
Als politie leek het goed te werken

2021-06-16 19:46 UTC, Ghoster524 commented
Het probleem lag bij de api, omdat het geen rol meestuurde. Ik heb er uren op gezeten, omdat ik niet wist waar het uberhaupt fout ging.. nu eindelijk dus wel. Een tip voor andere, een breakpoint te zetten bij de exception die bij #11 staat.

2021-06-17 09:59 UTC, imfi-jz requested changes
Het live bijwerken van de lobby gaat goed!
Het oppakken van een boef gaat nog niet helemaal goed.
De score van de agenten ging niet omhoog en bij de boef zag ik niks gebeuren. Maar in de spelnotificaties zag ik wel dat de boef was opgepakt, en in het speler overzicht van de app zie ik het ook.
![image](https://user-images.githubusercontent.com/10811551/122374556-c263d800-cf62-11eb-8538-6564d62045ea.png)

![image](https://user-images.githubusercontent.com/10811551/122374772-efb08600-cf62-11eb-8212-264ec753440a.png)


En ik had nog een bug gevonden: als ik als agent op een agent pin klik krijg ik een IndexOutOfBoundsError (misschien wel die die ik voorspelt had in mijn eerdere comment):
![image](https://user-images.githubusercontent.com/10811551/122374673-de677980-cf62-11eb-9372-62da719b07a1.png)

Ik denk dat ik straks nog een keer ga testen om te kijken of deze fouten consistent zijn.

2021-06-18 10:32 UTC, lderkzen requested changes
Als politie agent kan ik niet de dichtstbijzijnde boef zien

2021-06-18 10:36 UTC, lderkzen approved these changes, later dismissed
Works as intended

2021-06-19 13:47 UTC, imfi-jz submitted a review, later dismissed
Mijn probleem blijkt niet specifiek voor de "Gearresteerd" melding te zijn.

2021-06-21 12:33 UTC, merged