US#11 & Storyless#265
imfi-jz/SOPROJ11Q-Mobile pull request #46
Opened 2021-05-05 15:47 UTC by imfi-jz

Deze PR hoort bij ...
- Het politiebureau wordt weergegeven als plaatje;
- De buiten worden weergegeven als plaatje;
- Er is een icoontje voor het berichten knopje;
- De kleur van de pins reflecteert de rol van deze speler.

2021-05-05 18:06 UTC, Ghoster524 commented on Hunted Mobile/Hunted Mobile/Hunted Mobile/Model/GameModels/Player.cs
> +    public class Player : CustomModelErrorMessages<Player> {
Volgensmij moet je deze branch nog updaten met `main`, want dit zijn al oude wijzingen die nu wel op `main` staan

2021-05-05 18:08 UTC, Ghoster524 commented on Hunted Mobile/Hunted Mobile/Hunted Mobile/Repository/InviteKeyRepository.cs
> +            response.HasMultipleResults = true;
```suggestion
            var response = new HttpClientResponse() {
            HasMultipleResults = true,
            }
```

2021-05-06 11:39 UTC, Stupers submitted a review, later dismissed
Nice

2021-05-06 17:45 UTC, lderkzen requested changes
Ik moet zeggen dat de icoontjes het erg moeilijk maken om exact de locatie te weten. bijvoorbeeld bij de buit. Ligt de buit werkelijk net onder de image? Of misschien het image er op gecentreerd? etc etc. Ook is de cluster van buit een beetje rommelig met die icoontjes. Ik zou de icoontjes in ieder geval wat kleiner maken.

De beste optie zou zijn om gewoon de normale pins te pakken zoals ze er eerst uit zagen maar andere kleuren te geven.

2021-05-06 18:05 UTC, imfi-jz commented
> Ik moet zeggen dat de icoontjes het erg moeilijk maken om exact de locatie te weten. bijvoorbeeld bij de buit. Ligt de buit werkelijk net onder de image? Of misschien het image er op gecentreerd? etc etc. Ook is de cluster van buit een beetje rommelig met die icoontjes. Ik zou de icoontjes in ieder geval wat kleiner maken.
> 
> De beste optie zou zijn om gewoon de normale pins te pakken zoals ze er eerst uit zagen maar andere kleuren te geven.
> 
> De code ziet er wel prima uit overigens.

Ik ben het er deels mee eens maar eerlijk gezegd lijkt me dit iets voor Ernst om te bepalen. Als je inzoomt wordt het wel iets duidelijker waar het ligt, en het is ook fijn als de icoontjes niet te klein zijn (om er nog op te kunnen tappen). Ze zoomen namelijk niet mee met de kaart.

2021-05-06 20:39 UTC, Ghoster524 approved these changes
Het ziet er echt heel nice uit!

2021-05-06 20:41 UTC, Ghoster524 commented
> Het ziet er echt heel nice uit!

Je zou misschien nog wel iets kunnen doen dat politie niet op de pin kan drukken van een fout. Dat heb ik dus ook toegepast als politie die kan klikken op boeven. Gewoon controleren of de huidige player `is Police`. (niet perse fout, want dit komt niet door jouw branch)

2021-05-06 20:48 UTC, imfi-jz commented
> Je zou misschien nog wel iets kunnen doen dat politie niet op de pin kan drukken van een fout. 

Van een buit bedoel je? Als het goed is had ik dat wel gemaakt eerder in deze sprint.

2021-05-07 10:09 UTC, merged