#155 158 jesse
imfi-jz/SOPROJ11Q-Mobile pull request #50
Opened 2021-05-06 16:24 UTC by Stupers

Gebruik bij deze PR ook de PR van de API!

2021-05-06 19:03 UTC, imfi-jz requested changes
Het blokje om de tijd heen is een beetje te groot:

![image](https://user-images.githubusercontent.com/10811551/117351686-47f96000-aeae-11eb-9e96-821c00d79f96.png)

En de tijd tikt door wanneer het spel is afgelopen.

2021-05-06 19:51 UTC, lderkzen requested changes
Tijd lijkt te werken maar ik zie alleen mijn eigen pin en het spel pauzeren werkt niet.

2021-05-06 20:34 UTC, Ghoster524 submitted a review, later dismissed
Bij mij ziet het er mooi uit! Heb net getest en pauzeren en hervatten onderbreekt en hervart de timmer ook.

![image](https://user-images.githubusercontent.com/60692171/117362069-1b981080-aebb-11eb-87ac-7e3e62ac11b7.png)

2021-05-06 21:19 UTC, imfi-jz commented
> Tijd lijkt te werken maar ik zie alleen mijn eigen pin en het spel pauzeren werkt niet.

Dat klinkt als misschien de verkeerde API branch of cache problemen?

2021-05-07 08:30 UTC, imfi-jz approved these changes
De timer tikt nog door wanneer het spel afgelopen is. Maar het werkt verder goed en ziet er goed uit.

2021-05-07 08:30 UTC, imfi-jz commented on Hunted Mobile/Hunted Mobile/Hunted Mobile/ViewModel/MapViewModel.cs
> +        private DateTime dateTimeNow;
Misschien dat (een deel van) deze variabelen naar de Countdown klasse kunnen verplaatsen

2021-05-07 10:35 UTC, lderkzen approved these changes

2021-05-07 10:47 UTC, LeonNiekus approved these changes

2021-05-07 10:47 UTC, merged