#214_Martijn > Refactor MapViewModel
imfi-jz/SOPROJ11Q-Mobile pull request #59
Opened 2021-05-16 15:31 UTC by Ghoster524

2021-05-17 11:32 UTC, imfi-jz reviewed
Ziet er goed uit. 
2 opmerkingen:
- De standaard icoontjes van de kaart voor centreren en zoomen etc. staan niet helemaal goed uitgelijnd met het chat icoontje (bij mij iig). En volgens mij hoefde de zoom knopjes niet terug in de app.
- En ik denk dat de enum voor PlayerRole niet meer nodig is met mijn refactor (maar dit hoef je niet aan te passen).

2021-05-18 12:12 UTC, Stupers requested changes
Yes zelfde als bij Quinten, die standaard map buttons staan er en die overlappen inderdaad met de chat knop. Verders ziet het er wel goed uit

2021-05-18 17:30 UTC, Stupers submitted a review, later dismissed

2021-05-18 19:16 UTC, imfi-jz requested changes
De spelleider ontvangt geen bericht meer als een speler de spelgrens verlaat of betreed, de berichten komen niet in de database binnen (ik zit in de API op dev).

2021-05-18 20:50 UTC, Ghoster524 commented
Dit PR bestaat niet echt meer, want alle wijzingen zitten ook in de andere twee PR's

2021-05-19 09:30 UTC, Stupers approved these changes

2021-05-19 09:35 UTC, imfi-jz approved these changes

2021-05-19 10:24 UTC, Stupers approved these changes

2021-05-19 10:32 UTC, merged