#215 > Toast messages en catch afhandelingen
imfi-jz/SOPROJ11Q-Mobile pull request #65
Opened 2021-05-18 20:32 UTC by Stupers

2021-05-18 21:45 UTC, imfi-jz requested changes
Toast berichten zijn toch deze dingen?
![image](https://user-images.githubusercontent.com/10811551/118727360-ebddf680-b832-11eb-854a-a4bcb366f3a0.png)

Ik zie er namelijk geen van verschijnen als er een error optreed volgens mij.
En ik zie de spelers (namen) in de lobby niet meer.

2021-05-18 22:04 UTC, imfi-jz approved these changes
Ik heb de problemen van mijn eerste review zelf opgelost. De meldingen moesten via de main thread aangemaakt worden.

Er wordt nu wel elk interval een error melding weergegeven maar die error is opgelost in mijn refactor branch. Eventueel kunnen alle ongebruikte 'ex' of 'e' variabelen in de catches weggehaald worden zodat daar geen warning meer over komen.

2021-05-19 08:45 UTC, lderkzen commented
> Toast berichten zijn toch deze dingen?
> ![image](https://user-images.githubusercontent.com/10811551/118727360-ebddf680-b832-11eb-854a-a4bcb366f3a0.png)
> 
> Ik zie er namelijk geen van verschijnen als er een error optreed volgens mij.
> En ik zie de spelers (namen) in de lobby niet meer.

Nee Toasts zijn kleine popups onderin het scherm die maar voor een paar seconden blijven hangen.

2021-05-19 09:05 UTC, Ghoster524 approved these changes

2021-05-19 10:36 UTC, merged